### ISSUE TITLE
New Content

### ISSUE THREAD

**Issue by LinusGeffarth** [vaporberlin/vaporschool#1]
Hey there, I was wondering whether you were still generating new content for this page?  
I really appreciate the existing tutorials!

**Comment by fadylateef** [comment]
I've posted a reply on a tutorial for [Martin Lasek](https://www.youtube.com/channel/UCoLEXFUHIKXunm9QJjsAftw) and he replied : 

>  I‘m starting a Vapor series alongside this one in the upcoming week! Stay tuned 🙌🏻✨﻿

**Comment by LinusGeffarth** [comment]
Thanks for the info!
